language: node_js
node_js:
- '8'
dist: trusty
sudo: false
branches:
  except:
  - results
install:
- npm install
script:
- npm run code-check
- if [ "$TRAVIS_PULL_REQUEST_SLUG" = "Cimpress/react-cimpress-fulfillers-components" -o "$TRAVIS_PULL_REQUEST_SLUG" = "" -a "$TRAVIS_REPO_SLUG" = "Cimpress/react-cimpress-fulfillers-components" ]; then npm run translate; fi
- npm run compile
deploy:
  provider: npm
  email: TrdelnikSquad@cimpress.com
  skip_cleanup: true
  api_key:
    secure: FMTlGOBZIpzNhw6qCJ/x7e/l+mXqT4sf8IkPfb3mhSwOxUbQh+/c3G/BEAUeh/ohBscL/xCwiXhNT5LaoGQpMNlY1n6vDfgBNeBBJOd8REFbwbkd5Q3cUGqYmjm/PVtO3GSfXJjCE5geggELRtBGXy8cHAt4w0ixUSyNKOiWTvkDWb/wYDt+IJtXSC7x1gIRR1Kn/Ka8ozrjaVN2ndbYpT+ITSnGMhgmHJHpqD+ZhHkq8LmtezK2n4IubTRpvm+hu4bSEV9z4/C4ZClSgKMNxY+5YBXUed0tEFtzLi8TO4rLYjti6VeyMCaVE2Cr4afuf02QOzLqBxURowipJf1l0YvSOLr0KZKl4+YTtvKeJalEWStPSkhmvJPrAu27vp3vZLQV6eMNdWJ8bw2X5iWD5RWigk6MceU2xqd0cLkwEbqBVQuD/ELeEYzE5EvgEgUJcIZI9GRtdxcBZdBOUNH8LwK+YhZjIElRS9O7UHwMpnS5Fystbb/SuqAHySJljmWc7HYjmhjvMssGwkXG4gAi+eJHEATIokx2HkQEF7rp9BN8I015vgQ/tMRtSoMqh+H51gicUKdkqeYzThtgOEe+TcXnFKDsDAfF1394Lsk611G0N3Rcst/JxGYT7LpLH+TykuiJcgo/tl9vqeHDKydVg/0/DNHu8CEF9/0XOniUKuE=
  on:
    branch: master
    repo: Cimpress/react-cimpress-fulfillers-components
notifications:
  slack:
    rooms:
      secure: a/jYb0qBZMVz8W03LaxxZAwJbjRKECga2MNXH3UJoo6tguQ/ju+swjelhbZ5jk8BfiPe24hiN9eV/GVqd/GE/oTJrVlwnBiA0Dj+8SUMbpZJUmmQm99QTs/6AY0IyQmZBF2mocwzIhGrt23ql+iHWy3e3y29a66DBK6nm5ijljxZ2ZBycX8rbU10SgQebsKi73H1uS7kvKatd+zLzEvjOoN2DgdOGg46wTCO7qRLNrlz/4j+e+CLdV7OjGr9aDVnojJmA9qVFivRmwGkRpwSosFUVHwrL+R2ukjRf/BMLvkkt1DAytHlEwKoMoe9YxVO2EiNORxVldU2IM4w5AH3hFrxYXsXoqiW0zLwqwxD4rI8ze9hr4D9g1gUDyGu7F839u5XVS6eXwzaqY9D0xknG3OdJ/8sv9cfuyjIT37COA0AXFaOvJ+pM0mWpKUHpXlf7fVHTcn2efxqJdi48LIfad91AfrDn7SGRo6HU8GEtrMpRJ1OMxRq0GQZVcm83MWap8JI6kAwYn3Itm9CV2RXrhvXgjOimY7RNpbt9MDKQPoXqq1lVSF0eAcNL6jLIGo9NCnn4TaUC9fKUs9PWEPH8/K3nOsv7c7MTw/tXQSsK4T2Vb3ccPiDjmZG6khYC78s7vLPX/16DajImD1UyO22gWkDl3+mwTPqVOsdl7RA6jQ=
env:
  global:
  - secure: UGgls31kXAKZFHxL8DxC/5vp2JfzS5uwmfja/yWCRxiZx6Kretjj7uPDnoo0fJWvFzP1odGp85KqB3te92k1FSn7jrtFJOmKSb9yo7d5RTgdeU72f2BoYvaSJSOQYCThNSvWnDjfAvGwAfgfSlco4gd9mgf23XTIlDAeEXqoLGKavau0vguzwfb9QG6r1kIGcDgOMqJpmfYuHNaL6RiKv4uvoIug4HyXhplZ9eF89fdT8UC3VbPpeLUGmebgFBNSJXiypq4Xs34pAlwVAc7AOAqp2KLl+izHz9grUYk4YxDShXwA3xCUeQlQoRF+x99EXYhjxKAaFXCzHq5ybUvSMo8Pt+GSlBvHjwqStv8RITnXGwDKA07z1s2yE1rwsuj/PKPJAm9ccD/KF+hxU3GWoiUkifM0ng1gN78pPUtRb6k63NiFBO34aijE+6O65VuHmwhQgmlWT19r0YZZR0+KUjBcVOhJuuVmPxBi4n5NrObz+SoJYRwxBKKvziltMwfCotakf2GdUkvXhO7LGQ3nqR7xq/uvyapj/0azlzQmyGxeQdltUl8CLP3lW006ksZi43H972R9QRmG+X1OqDnv+j+pIXa59x8wOWKAOSzsmlD8JT3LJwWJKARxVEL8JhiWwqQmJK51f4XmNQJUoZEfCRf8+axTq2cBSzK5NM+MbFU=
  - secure: UoR95BqwQLboWiNurgaNUBNQRE8sAD9QOm8I1Il9AVxXad9OMLGgPX0zIMy8EK2aEjcorwCjnM1omaE33l7opABCYktq9NZymN3csWGtPRBI7KqFS/RGv5tM5jp5OdJP058XJTksUHjUrGK+Gw0UehJuBu+N5peB5EvdlN+lf+3MGQtrgV1HRZpyVyT7bGSmB+tck3GX9wRzA51FGtq/gULuNHcTRMePXUPWnr5igAJjyALY5CaWjZrIo8UeHdhylUeohQQN7u7qjjvbof1XFD3d4HvvMgZNKTbIC3v9aPlHQPt397nyyM8J570jz1aUov3A48m/zePPSb1p5ULE+lPOOKDTQXAk6AZU6u5KHOtybZY0xUhmdEytGgEPMHa0/f1Ir4qysoPkXQGzRnerACY2CsJALXIw9GDedrwMLC2f7M4uo7W3WKQxI2KnoIFnJ+ztYLSgW9uT3EMxJVl54mNSnaJ+d73lxgHcki95XzRktIkYgXbIjNPpiE2d97wf6mFmq+TWTRJU04Yv6+cGQXgVlgr53BzQRaoFiY4fnj+rSQYEnf/gP3xhReHRdDWjZ4hs8iZvPWUfPLBcDaaO5dEdz5L5htji3WBtPQQNOdZk59YclwI/DHJpEKfjbNmAtGX+Q2rf0wH9oeBtjTeguRhLPfTlu6VAfW8ige3M41Q=
