language: node_js
node_js:
- '6'
dist: trusty
sudo: false
branches:
  except:
  - results
install:
- npm install
script:
- npm run code-check
- npm run-script build
- node node_modules/grunt-cli/bin/grunt build
deploy:
  provider: npm
  email: ivan.stanishev@cimpress.com
  api_key:
    secure: G89qZ57xAB+SR1j/FHPmqu9y0OpscPdb9vXyj0g3mbGuECpjJbJ2S77cJP+jsUogux/UimuzNy/z81hAwasEUI6JhUHl0ThVHvu38ZM1oI3BcKyRgz9ViZ87RpKXxOfxn9jClthFo9KgIUHTkVAk5Yh+hnPcnX+8Sb1qpEFD2zIiim2lI8B8xQSJt2vbp6O/Yce2Jg6sFAWFWxfrsId4c7Qguuo8py+UAqOTbzPBbDL5NfRu6CJbfWAFOyGmz9jq3H2VjvfYkC74XXk3qtu8kMWB+VYb4hZapVxuxkqUlh4X7v9rPQNAc44uHyY7pjBkzhT9K/2tGQ78p2s0zf4Ub0OrNpRcLxI5fzCEnCRF+mkFTlWl8G5xFpdREU/PdEwFk7a9AJogMJ/UNv1ZO+u3ui+DHdC+FS+2ngvF0PDTfXe1THd5Os91VQDPm+UUF7PuqIz7kvjokWxmkOU4+VQJaoApO1SgEDzqFoWQ9dJE60I+LtF2hZu9rpPBgUhBTXjAexyYVat4CSwOyTxQ8L6N9osPvzB2NZFd0Fum20PI2WSdFJtUIqGqAavqB0L9ohHe4l5O1fvLxHcAFBz6zel7oSBn6pvPerFyF5uGrzGaTVM4Xb25HlZmFCCMRNmGPNgNIR4A9Jub8Jnc3vN5pl3/lKy6w+twJte9aBqSyXY8rho=
  on:
    branch: master
notifications:
  slack:
    rooms:
      secure: a/jYb0qBZMVz8W03LaxxZAwJbjRKECga2MNXH3UJoo6tguQ/ju+swjelhbZ5jk8BfiPe24hiN9eV/GVqd/GE/oTJrVlwnBiA0Dj+8SUMbpZJUmmQm99QTs/6AY0IyQmZBF2mocwzIhGrt23ql+iHWy3e3y29a66DBK6nm5ijljxZ2ZBycX8rbU10SgQebsKi73H1uS7kvKatd+zLzEvjOoN2DgdOGg46wTCO7qRLNrlz/4j+e+CLdV7OjGr9aDVnojJmA9qVFivRmwGkRpwSosFUVHwrL+R2ukjRf/BMLvkkt1DAytHlEwKoMoe9YxVO2EiNORxVldU2IM4w5AH3hFrxYXsXoqiW0zLwqwxD4rI8ze9hr4D9g1gUDyGu7F839u5XVS6eXwzaqY9D0xknG3OdJ/8sv9cfuyjIT37COA0AXFaOvJ+pM0mWpKUHpXlf7fVHTcn2efxqJdi48LIfad91AfrDn7SGRo6HU8GEtrMpRJ1OMxRq0GQZVcm83MWap8JI6kAwYn3Itm9CV2RXrhvXgjOimY7RNpbt9MDKQPoXqq1lVSF0eAcNL6jLIGo9NCnn4TaUC9fKUs9PWEPH8/K3nOsv7c7MTw/tXQSsK4T2Vb3ccPiDjmZG6khYC78s7vLPX/16DajImD1UyO22gWkDl3+mwTPqVOsdl7RA6jQ=
