language: node_js
node_js:
- '6'
dist: trusty
sudo: false
branches:
  except:
  - results
addons:
  chrome: stable
install:
- npm install
script:
- npm run code-check
- npm run-script build
- node node_modules/grunt-cli/bin/grunt build
after_script:
- node node_modules/grunt-cli/bin/grunt publish
deploy:
  provider: npm
  email: ivan.stanishev@cimpress.com
  api_key:
    secure: G89qZ57xAB+SR1j/FHPmqu9y0OpscPdb9vXyj0g3mbGuECpjJbJ2S77cJP+jsUogux/UimuzNy/z81hAwasEUI6JhUHl0ThVHvu38ZM1oI3BcKyRgz9ViZ87RpKXxOfxn9jClthFo9KgIUHTkVAk5Yh+hnPcnX+8Sb1qpEFD2zIiim2lI8B8xQSJt2vbp6O/Yce2Jg6sFAWFWxfrsId4c7Qguuo8py+UAqOTbzPBbDL5NfRu6CJbfWAFOyGmz9jq3H2VjvfYkC74XXk3qtu8kMWB+VYb4hZapVxuxkqUlh4X7v9rPQNAc44uHyY7pjBkzhT9K/2tGQ78p2s0zf4Ub0OrNpRcLxI5fzCEnCRF+mkFTlWl8G5xFpdREU/PdEwFk7a9AJogMJ/UNv1ZO+u3ui+DHdC+FS+2ngvF0PDTfXe1THd5Os91VQDPm+UUF7PuqIz7kvjokWxmkOU4+VQJaoApO1SgEDzqFoWQ9dJE60I+LtF2hZu9rpPBgUhBTXjAexyYVat4CSwOyTxQ8L6N9osPvzB2NZFd0Fum20PI2WSdFJtUIqGqAavqB0L9ohHe4l5O1fvLxHcAFBz6zel7oSBn6pvPerFyF5uGrzGaTVM4Xb25HlZmFCCMRNmGPNgNIR4A9Jub8Jnc3vN5pl3/lKy6w+twJte9aBqSyXY8rho=
  on:
    branch: master
notifications:
  slack:
    secure: hcLcEUCHCua4mqVMhP1vXIsxaSJ9/u30xGIswPPg9iNdraL6V0CGbO9AUddP+Wpr+UEOxFhqA8aknZ6U0uDFg3Mi5h/IWerLSbFaJzuQtqoVWQuHFVkO4KgCRZy7Ihsk1U3e/JhsZIndmZ7/sMuN47K1naoEvahcbm7FrH8o7rUIFMrmHsGB7yIXtdbVcJINC8Ii5EN95ncGE3zOwVOBd5XMq8RYvxQWDEoyHxewJ3pkYW88Gss9Zjvs3SlOs3cq4jZyaB75DSHIZ1eeZ0A25/RANBdNH8BJcjtg4bMXk6KdG1t/9sn+KuHBU2EOwCIdRCzuuh2JXDA0wXh6oB7HDL484Kgq/rV/slEAVQXULMU/08txtZuf6DFDkVAB2E94SjzIWYUiOgzmbjEDbxs5SyuUJLu3Ciqua3Zpg2nDRQ4mvsOsAKW8CZxOapnM+29LlbNA4H0cfSrajLPwSt9LeWilFvoFvJ9KqfIzYDSxdoZFCMGfTOW9rlPL3zRWRYmn1rlQdCAoh751+wfvIXN5uU9sLWFBGt2jWqor0Lg4XtvFVGWCLtzfI0zh8aaBGihIVtsTCKeIC5mtFj6d83W+T4+WuV4niHnp2Xch9fVMLWThl+XuIDYRhG6cSrN8wmOZR+w6XJELBuzPhJ1qNGKxHJ9J5kgN5f04EUmTCvDmSVg=
env:
  global:
    secure: R4sbWJmvaFSvehd0bjDtL7v5PrYLWqDdI2UVdjFlI/1ruAktJWbJ6fP42FF3vM9wJ5asQvmGAIxFkS+sl5N4AnLUxifIMvl4WpSY01oTCY5hmj/wHmYXeVKCHnx7lWwm0mHSeV0MWBbgS7AlFnhTD5fb6L9kbGKmVU8Q6vZk/ADHysWp6xXZ1D+uR+cmVbkhyPlgBlMNbFzMMjyVvbBBq3N5FK97Y7XuIC0V+VUlW+WoIu5IL5AnVVfq068w29XQeFOc7vPDP47Z9pYnH62PIu+oHzM4E0acZwideeANo7/0I6DQHtWrRoJj9b6K4j0QLTmZNjmyl2YjU241qcj2+wOzZrBZNgCbBW6io2Khf3kKMVEVhiWJ1Y7XG0mNXNv56KFazdXAa5qCDM4O9j0WX6Vg08mv3cVO1HHAKM9mo+NgYrUZaEYY4zvFrjP5BGY1rcfwq2yamf+DJXaQc9vZpktIYK8S6P5P/0o7IVVzLlN8Nf8p04OSCTO8KYmwaAta0CU4/W9JXHqOvJPmkYpjod47U6C82/0BA5sCw8GbTC2PDZRWA0Vss0QeiEGeRyoxBmxGkOFljCd7ix4a3cY+GGvRSj2sLRTzW8bHsvO60dKYiPoCdvUz8Gqvp33MgWvtsjyr+3d1rA6NYUlrlYWKtymQmpyyGX69VsEZAQ3IP58=
